name: egresocovid19
description: El app de tus negocios favoritos

publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: '>=2.13.0 <3.0.0'

dependencies:
  animations: ^2.0.1
  auto_size_text: ^2.1.0
  beamer: ^0.14.1
  bubble_tab_indicator: ^0.1.6
  cached_network_image: ^3.1.0
  carousel_slider: ^4.0.0
  dartz: ^0.10.0-nullsafety.2
  dio: ^4.0.0
  extended_image: ^4.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^7.1.0
  flutter_blurhash: ^0.6.0
  flutter_localizations:
    sdk: flutter
  flutter_lyform: ^0.1.0+12
  flutter_staggered_grid_view: ^0.4.0
  flutter_svg: ^0.22.0
  flutter_web_plugins:
    sdk: flutter
  freezed_annotation: ^0.14.2
  get_it: ^7.2.0
  google_fonts: ^2.1.0
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  injectable: ^1.5.0
  intl: ^0.17.0
  json_annotation: ^4.0.1
  like_button: ^2.0.3
  path_provider: ^2.0.2
  pretty_dio_logger: ^1.2.0-beta-1
  responsive_builder: ^0.4.1
  retrofit: ^2.0.1
  share_plus: ^2.1.4
  shared_preferences: ^2.0.6
  shimmer: ^2.0.0
  sliding_up_panel: ^2.0.0+1
  smooth_page_indicator: ^1.0.0+2
  supabase: ^0.2.5
  url_launcher: ^6.0.9
  uuid: ^3.0.4

dev_dependencies:
  build_runner: ^2.1.1
  flutter_launcher_icons: ^0.9.1
  flutter_test:
    sdk: flutter
  freezed: ^0.14.2
  injectable_generator: ^1.4.1
  json_serializable: ^4.1.4
  lint: ^1.6.0
  retrofit_generator: ^2.0.1

flutter:
  uses-material-design: true

flutter_icons:
  android: 'launcher_icon'
  adaptive_icon_background: 'assets/icon/background.png'
  adaptive_icon_foreground: 'assets/icon/foreground.png'
  ios: false
  image_path: 'assets/icon/icon.jpg'
