name: gen404
on:
  workflow_dispatch:
  push:
    branches: [ deploy ]
jobs:
  gen404:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: canastro/copy-file-action@master
        with:
          source: index.html
          target: 404.html
      - uses: stefanzweifel/git-auto-commit-action@v4
